CREATE TABLE IF NOT EXISTS Todo(
  id IDENTITY PRIMARY KEY,
  done BOOLEAN,
  TEXT VARCHAR
);
DELETE FROM Todo;
INSERT INTO Todo VALUES(1, TRUE, 'Do something');
INSERT INTO Todo VALUES(2, FALSE, 'Do something else');
INSERT INTO Todo VALUES(3, TRUE, 'Test application');